spring:
  application:
    name: pizzaria
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG

server:
  port: 8080

jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://name-server:8761/eureka/}
  instance:
    prefer-ip-address: true

estoque:
  service:
    url: ${ESTOQUE_SERVICE_URL:http://estoque-service:8001}

tax:
  strategy: ${TAX_STRATEGY:LC 123/2006}

politica:
  desconto: ${POLITICA_DESCONTO:SemDesconto}