server:
  port: 8002

spring:
  application:
    name: entrega-service
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

pizzaria:
  service:
    url: ${PIZZARIA_URL:http://pizzaria:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://name-server:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.pizzaria.entrega: DEBUG
