server:
  port: 8765

spring:
  application:
    name: gateway-service
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  cloud:
    gateway:
      routes:
        - id: pizzaria-service
          uri: lb://pizzaria
          predicates:
            - Path=/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://name-server:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}
